/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e5e2e1",
        "inverse-primary": "#006e2c",
        "tertiary-container": "#babbbb",
        "on-secondary": "#313030",
        surface: "#131313",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-dim": "#131313",
        "on-primary-fixed-variant": "#00531f",
        "on-primary-fixed": "#002108",
        "secondary-container": "#4a4949",
        "on-error-container": "#ffdad6",
        "surface-tint": "#34e36a",
        "primary-fixed": "#69ff89",
        "primary-container": "#1ed760",
        "secondary-fixed-dim": "#c8c6c5",
        tertiary: "#d6d7d7",
        background: "#131313",
        "on-surface-variant": "#bbcbb8",
        "error-container": "#93000a",
        error: "#ffb4ab",
        "on-secondary-fixed-variant": "#474646",
        "on-secondary-fixed": "#1c1b1b",
        outline: "#859583",
        "surface-container-highest": "#353535",
        "on-tertiary-container": "#494b4b",
        "surface-container-low": "#1c1b1b",
        "inverse-on-surface": "#313030",
        "inverse-surface": "#e5e2e1",
        "on-tertiary": "#2f3131",
        "surface-variant": "#353535",
        "on-tertiary-fixed-variant": "#454747",
        "on-primary-container": "#005721",
        "surface-container": "#201f1f",
        "on-background": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "on-error": "#690005",
        "tertiary-fixed": "#e2e2e2",
        secondary: "#c8c6c5",
        "on-primary": "#003913",
        "on-secondary-container": "#bab8b7",
        "surface-container-high": "#2a2a2a",
        primary: "#4cf479",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed": "#1a1c1c",
        "primary-fixed-dim": "#34e36a",
        "surface-bright": "#393939",
        "outline-variant": "#3c4a3c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "24px",
        lg: "40px",
        "margin-mobile": "16px",
        sm: "12px",
        gutter: "24px",
        xs: "4px",
        base: "8px",
        "margin-desktop": "32px",
        xl: "64px",
      },
      fontFamily: {
        vibe: ["Archivo Black", "Arial Black", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-bold": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "label-bold": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "1.5", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
